version: '3'
services:
  backend:
    build: .
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      # - name=${PORT}
      - PORT = 5000
      - MONGODB_CNN = mongodb://database/test
  database:
    image: mongo 
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'